import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Assaf CRM',
  // description: 'Generated by create next app',
}

interface ILayoutProps{
  children: React.ReactNode
}

export default function RootLayout({children}:ILayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
